### ISSUE TITLE
Not possible to declare an healtcheck in docker compose

### ISSUE THREAD

**Issue by chess4ever** [primait/localauth0#79]
We are using localauth0 in the dev environment through docker compose and with version 0.5.0 of the image it was possible to have a proper healthcheck like this one:
```
healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/3000'
      interval: 2s
      timeout: 5s
      retries: 5
```

With the latest version it is not possible anymore to have an healthcheck since there are no shell or other networking tools installed in the image.
