### ISSUE TITLE
Issues with config in docker compose

### ISSUE THREAD

**Issue by jesse-peters** [primait/localauth0#87]
I'm able to run the project in docker compose, and got everything working. However, I'm not able to set the config settings at all, it uses the defaults no matter what I do.

I have tried setting both `LOCALAUTH0_CONFIG_PATH` and `LOCALAUTH0_CONFIG` in various configurations.

With the rust log level turned up I am not able to see [this error ](https://github.com/primait/localauth0/blob/146d988dcd305ec40f61c4d9f7c0a1992c6f9796/src/config.rs#L82-L84) when both are set.

**Comment by cottinisimone** [comment]
Hello @jesse-peters , yes, configuration it's a bit tricky and might be better documented. Have you tried using a volume and set the env var using the internal path? Something that might look like this:

```yaml
environment:
  LOCALAUTH0_CONFIG_PATH: /etc/localauth0.toml
volumes:
  - ./localauth0.toml:/etc/localauth0.toml:ro
```
